### ISSUE TITLE
Deployer hangs after pushing to Heroku

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-deploy#13]
I just ran `travis-deploy deploy production` and this is the last output I see:

```
To git@heroku.com:[PROJECT]-production.git
   1234567..1234567  HEAD -> master
```

Then the process just hangs.

This happens almost every time I deploy.

**Comment by sarahhodne** [comment]
The command finished eventually, but it took a long time. I'm guessing 5-10 minutes from when I ran it to when it finished.

**Comment by roidrage** [comment]
Is this due to an issue in the deploy script?

Heroku deploys sometimes have the tendency of being stalled for unknown reasons unfortunately, so I'd guess this is the case here too.

**Comment by sarahhodne** [comment]
It hangs after the git push has finished, so I don't think that's due to Heroku? I see all of the Heroku deploy output.

**Comment by roidrage** [comment]
The git push to Heroku is part of the deploy process, it triggers all the following commands and steps on Heroku's end.

I've ran quite a few deploys today and had hangs in all kinds of places of the process, so I'd write this off as a similar one. Unless of course, you're seeing this every time you deploy.

**Comment by sarahhodne** [comment]
I'm still seeing this every time I deploy.

**Comment by sarahhodne** [comment]
Also, when I deploy manually (do all the steps without the script), there's no delay after the push.

**Comment by sarahhodne** [comment]
This doesn't happen on 1.9.3, only on JRuby (1.7.2 and 1.7.3). On 1.9.3 it immediately exits at the place where JRuby hangs.
