### ISSUE TITLE
Error fetching public key while encrypting environment variable

### ISSUE THREAD

**Issue by mariusbutuc** [travis-ci/travis-deploy#9]
I'm using `travis (0.0.6)` and I get the same error as described in [Use https url to retrieve public key](https://github.com/travis-ci/travis-cli/pull/2):

> [bdu-padrino (master)]$ travis encrypt mariusbutuc/bdu-padrino MY_SECRET_ENV=super_secret
> 
> About to encrypt 'MY_SECRET_ENV=super_secret' for 'mariusbutuc/bdu-padrino'
> 
> There was an error while fetching public key, please check if you entered correct slug

even if I'm editing `lib/travis/cli/secure_key.rb` to
- use either **https** or http URL to retrieve the public key, 
- either skip the **SSL certificate verification** or not.

What else can I check to ensure encrypting works?

---

Also in the browser, [travis-ci.org/mariusbutuc/bdu-padrino.json](https://travis-ci.org/mariusbutuc/bdu-padrino.json) shows _Loading_ forever...

What's expected to be rendered here?

**Comment by mariusbutuc** [comment]
Version 0.0.6 &mdash; or any version prior to 0.0.10 &mdash; fails because it's not using [the new endpoint for keys](https://github.com/travis-ci/travis-cli/commit/0cea3baf8d754cd8c7723c5b17143655cb949612). 

To fix it, simply update `lib/travis/cli/secure_key.rb` to [the one in v 0.0.10](https://github.com/travis-ci/travis-cli/blob/0cea3baf8d754cd8c7723c5b17143655cb949612/lib/travis/cli/secure_key.rb).

**Comment by sarahhodne** [comment]
(You could also update the gem)
